### PR TITLE
Fixes number of issues raised in issue #66

### PR DESCRIPTION
**Pull request by jaapbrasser**
# Description

Terraform Provider Development Program - Review

## Related Issue

Relates to issue #66 

## Motivation and Context

Provider Development

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **[CONTRIBUTION](https://github.com/rubrikinc/rubrik-provider-for-terraform/blob/master/CONTRIBUTING.md)** document.
- [X] I have updated the CHANGELOG file accordingly for the version that this merge modifies.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jaapbrasser** [comment]
@shamsway Could you take a look at this?

**Comment by shamsway** [comment]
@jaapbrasser This looks good but I think you want to merge this into the certification branch, not devel

**Comment by jaapbrasser** [comment]
@shamsway Updated it to the correct branch, thanks for spotting that Matt!

**Comment by rfitzhugh** [comment]
@jaapbrasser @shamsway  is this ready to be merged?

**Comment by shamsway** [comment]
> @jaapbrasser @shamsway is this ready to be merged?

absotutely!

**Pull request merged**
